# Generated by Django 5.1.4 on 2025-01-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=14)),
                ('area', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('marriageDate', models.CharField(max_length=11)),
            ],
        ),
    ]
