# Generated by Django 5.1.4 on 2025-01-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhome', '0003_alter_contact_area_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='place',
            field=models.CharField(default='lucknow', max_length=50),
        ),
    ]
