# Generated by Django 5.1.4 on 2025-01-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhome', '0004_gallery_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmailId', models.CharField(max_length=50)),
                ('review', models.TextField(max_length=100)),
                ('date', models.DateField()),
                ('stars', models.FloatField(max_length=5)),
            ],
        ),
    ]
