# Generated by Django 5.1.4 on 2025-01-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhome', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='gmailId',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=300),
        ),
    ]
