# Generated by Django 4.2.1 on 2025-03-06 09:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhome', '0006_alter_review_gmailid_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='gallery_image'),
        ),
    ]
