# Generated by Django 4.2.1 on 2025-03-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhome', '0008_alter_gallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('marriageDate', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='area',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='marriageDate',
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
